# Server
server.port=8088

# Application
spring.application.name=user-service

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/user_service}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user_service}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:user_service_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8181/realms/hrbp-llms/protocol/openid-connect/certs}

# Keycloak
keycloak.auth-server-url=${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8181}
keycloak.realm=${KEYCLOAK_REALM:hrbp-llms}
keycloak.admin-client-id=${KEYCLOAK_ADMIN_CLIENT_ID:user-service-admin}
keycloak.admin-client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET:mkqoljQy1nukBP9sH3cZ8xl1Q8LLcTrn}
keycloak.frontend-client-id=${KEYCLOAK_FRONTEND_CLIENT_ID:frontend-client}

# Springdoc / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Actuator
management.endpoints.web.exposure.include=health,info